trigger:
  batch: true
  branches:
    include:
      - refs/tags/*
  paths:
    include:
      - interceptor/*
      - .azure/*

pr: none

variables:
  CONTAINER_REGISTRY: choreocontrolplane.azurecr.io
  REPOSITORY: choreoipaas/dp-keda-http-add-on-interceptor
  TAG: $(Build.SourceBranchName)

jobs:
  - job: DockerReleaseScanAndPush
    steps:
      - task: Docker@2
        displayName: 'Build Docker Image'
        inputs:
          command: build
          containerRegistry: 'wso2choreo-control-plane-acr'
          repository: $(REPOSITORY)
          tags: $(TAG)
          Dockerfile: "interceptor/Dockerfile"
          buildContext: "."
      - template: install/install-trivy.yaml@common-templates
      - script: |
          set -eo pipefail
          trivy image --exit-code 1 \
          --severity HIGH,CRITICAL \
          --no-progress \
          --ignorefile .trivyignore \
          $(CONTAINER_REGISTRY)/$(REPOSITORY):$(TAG)
      - task: Docker@2
        displayName: 'Push Docker Image'
        inputs:
          command: push
          containerRegistry: 'wso2choreo-control-plane-acr'
          repository: $(REPOSITORY)
          tags: $(TAG)

