resources:
  repositories:
    - repository: common-templates
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      endpoint: wso2-enterprise

trigger:
  batch: true
  branches:
    include:
      - release/v0.8.0
  paths:
    include:
      - interceptor/*
      - .azure/*

pr: none

variables:
  - name: CONTAINER_REGISTRY
    value: choreocontrolplane.azurecr.io
  - name: REPOSITORY
    value: choreoipaas/dp-keda-http-add-on-interceptor
  - name: TAG
    value: $(Build.SourceBranchName)-$(Build.SourceVersion)

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: Docker@2
    displayName: "Docker Build"
    inputs:
      command: build
      Dockerfile: "interceptor/Dockerfile"
      buildContext: "."
      containerRegistry: "wso2choreo-control-plane-acr"
      repository: $(REPOSITORY)
      tags: |
        $(TAG)
        latest
  - template: install/install-trivy.yaml@common-templates
  - script: |
      set -eo pipefail
      trivy image --exit-code 1 \
      --severity HIGH,CRITICAL \
      --no-progress \
      --ignorefile .trivyignore \
      $(CONTAINER_REGISTRY)/$(REPOSITORY):$(TAG)
  - task: Docker@2
    displayName: "Push Docker image"
    inputs:
      command: push
      containerRegistry: 'wso2choreo-control-plane-acr'
      repository: $(REPOSITORY)
      tags: |
        latest
        $(TAG)
