resources:
  repositories:
    - repository: common-templates
      type: github
      name: wso2-enterprise/choreo-common-pipeline-templates
      endpoint: wso2-enterprise

trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - scaler/*
      - .azure/*

pr: none

variables:
  - name: CONTAINER_REGISTRY
    value: choreocontrolplane.azurecr.io
  - name: REPOSITORY
    value: choreoipaas/dp-keda-http-add-on-scaler
  - name: TAG
    value: $(Build.SourceVersion)

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: Docker@2
    displayName: "Docker Build [keda-http-scaler]"
    inputs:
      command: build
      Dockerfile: "scaler/Dockerfile"
      buildContext: "."
      containerRegistry: "wso2choreo-control-plane-acr"
      repository: $(REPOSITORY)
      tags: |
        $(TAG)
        latest
  - template: install/install-trivy.yaml@common-templates
  - script: |
      set -eo pipefail
      trivy image --exit-code 1 \
      --severity HIGH,CRITICAL \
      --no-progress \
      --ignorefile .trivyignore \
      "choreocontrolplane.azurecr.io/choreoipaas/dp-keda-http-add-on-scaler:$(TAG)"
  - task: Docker@2
    displayName: "Push Docker image"
    inputs:
      command: push
      containerRegistry: 'wso2choreo-control-plane-acr'
      repository: $(REPOSITORY)
      tags: |
        latest
        $(TAG)
  - template: update-image-in-cp-overlays.yml@common-templates
    parameters:
      DOCKER_IMAGE_LIST:
        - $(CONTAINER_REGISTRY)/$(REPOSITORY):$(APP_REVISION)
